### ISSUE TITLE
Relax RDoc dependency

### ISSUE THREAD

**Issue by voxik** [zzak/sdoc#101]
You keep specifying strict RDoc dependency, but what is the purpose actually?

In 38d0609532a34699f9db0b1af9c4cfcddb68d7b5, you bumped the dependency to "5.0.0.beta2" without much explanation. Then in d996e81bd1d4f9e30353 it was bumped again to "5.0.0" just because of Ruby 2.4, but it does not mean it does not work with older version of RDoc. 

May I suggest to change the dependency on RDoc to ">= 4.0.0" and problem solved. Or at least to "~> 5.0". You don't want to change the dependency again as soon as RDoc 5.0.1 is released I guess ...

**Comment by zzak** [comment]
@voxik Specifying ">=" will cause warnings with bundler, but I'm open to suggestions.. maybe we can say "~> 5.0" since I'd like to ultimately replace this gem w/ `rdoc` itself by 6.0

**Comment by voxik** [comment]
> Specifying ">=" will cause warnings with bundler

I was not aware of this.

> maybe we can say "~> 5.0"

Works for me. Thx.
