### ISSUE TITLE
Tag v1.0.0.rc3

### ISSUE THREAD

**Issue by manuelmeurer** [zzak/sdoc#117]
It seems that v1.0.0.rc3 is not tagged, at least it doesn't appear under [releases](https://github.com/zzak/sdoc/releases).

Could you add the tag to the [commit](https://github.com/zzak/sdoc/commit/3b5ec3fa2622fcc5d2b68975d7257a0347b7a567)?
Thanks!

**Comment by robin850** [comment]
It should be fixed now ; thanks for catching this !
