### ISSUE TITLE
Any chance of getting a new version?

### ISSUE THREAD

**Issue by mariochavez** [zzak/sdoc#121]
Hey @zzak !

What are your plans for releasing a new version with latest fixes?

Cheers,
Mario

**Comment by zzak** [comment]
Hi @mariochavez!

Let me see what I can do 👼

**Comment by robin850** [comment]
Hey there !

Sorry, it's my bad if the release was always postponed. Version 1.0.0 has been pushed to Rubygems. Have a nice day ! 🎉 🙂
