### ISSUE TITLE
Version does not provide correct output

### ISSUE THREAD

**Issue by voxik** [zzak/sdoc#125]
The ```--version``` flag used to be broken in some previous versions. Now it works, but it outputs the RDoc version instead of SDoc version:

~~~
$ ruby -Ilib ./bin/sdoc --version
6.0.2
~~~

Not sure this is expected.

**Comment by robin850** [comment]
Hi @voxik,

Thanks for reporting, this has been fixed with 39e6cae ; we should cut 1.0.1 soon.
