### ISSUE TITLE
No overflow scroll on sidebar tree and results

### ISSUE THREAD

**Issue by cveneziani** [zzak/sdoc#143]
Would it be possible to replace `overflow: scroll` property on `.tree` ad `.result` divs by `overflow: auto`?

On a Linux Firefox, with `overflow: scroll`, the browser always displays the scroll area even when there's no need of a scroll 
(as described in MDN https://developer.mozilla.org/en-US/docs/Web/CSS/overflow )

### Overflow: scroll

<details>
  <summary>Tree div</summary>
  <img src="https://user-images.githubusercontent.com/50518/98821336-b5609280-242f-11eb-9348-eb5e56a3b586.png" alt="Tree div with overflow: scroll">
</details>

<details>
  <summary>Result div - no scroll needed</summary>
  <img src="https://user-images.githubusercontent.com/50518/98821333-b5609280-242f-11eb-94b4-202c35fc5968.png" alt="Result div - no scroll needed">
</details>

<details>
  <summary>Result div - with two scroll areas</summary>
  <img src="https://user-images.githubusercontent.com/50518/98821332-b4c7fc00-242f-11eb-9f7e-69681104f229.png" alt="Result div - with double scroll areas">
</details>

### Overflow: auto

<details>
  <summary>Tree div - no scroll area</summary>
  <img src="https://user-images.githubusercontent.com/50518/98821584-0a040d80-2430-11eb-8c98-fdaccfa6418a.png" alt="Tree div with overflow: auto">
</details>

<details>
  <summary>Result div - no area needed</summary>
  <img src="https://user-images.githubusercontent.com/50518/98821581-08d2e080-2430-11eb-9c02-a8a74baba806.png" alt="Result div - no scrollbar">
</details>

<details>
  <summary>Result div - with one scrollbar only when needed</summary>
  <img src="https://user-images.githubusercontent.com/50518/98821582-096b7700-2430-11eb-9428-7c951a3aab6d.png" alt="Result div - with one scrollbar only when needed">
</details>

**Comment by rafaelfranca** [comment]
Yes. Can you open a PR changing it?

**Comment by cveneziani** [comment]
Sure, I'll try to open one this weekend.

**Comment by p8** [comment]
@cveneziani This would probably require changes to:
https://github.com/zzak/sdoc/blob/master/lib/rdoc/generator/template/rails/resources/css/panel.css
It's currently a bit difficult to test things locally, as the Turbolinks implementation requires absolute paths for javascript and css.

**Comment by cveneziani** [comment]
I finally found time to open a pull request.

I've been able to test locally thanks to the rack application config.

> This would probably require changes to:
> https://github.com/zzak/sdoc/blob/master/lib/rdoc/generator/template/rails/resources/css/panel.css

I was wondering, what is the purpose of the one available within the `sdoc` folder?
This one: https://github.com/zzak/sdoc/blob/master/lib/rdoc/generator/template/sdoc/resources/css/panel.css
Last update: August 2017

**Comment by p8** [comment]
@cveneziani The `sdoc` folder is for a different layout, which isn't used by rails.
It's currently broken because it's still using frames.
