### ISSUE TITLE
Rails template using absolute paths makes checking on local more difficult

### ISSUE THREAD

**Issue by CodeMeister** [zzak/sdoc#146]
The rails template in 2.0.2 is using absolute paths for resources and pages:
```ruby
<link rel="stylesheet" href="/css/main.css"...
```

This works great for a web-server, but it's a problem when developing and you want to check the documentation by loading `index.html` directly in a browser.

Will you consider reverting the paths to be relative again?

**Comment by p8** [comment]
@CodeMeister to run it locally as a rack app: 

      rackup config.ru

Turbolinks 5 requires these paths to be absolute. Maybe things will change in Turbolinks 6

**Comment by CodeMeister** [comment]
@p8 That makes sense.  Many thanks for the quick response 👍

**Comment by sofianegargouri** [comment]
Hi ! 
So we're not able to load HTML directly anymore ? 
We're currently hosting our doc on Github Pages so we have a prefix in the URL path. Are we not able to do that anymore ?

**Comment by p8** [comment]
@sofianegargouri Maybe it would work if change the rel_prefix to your prefix.. 
https://github.com/zzak/sdoc/blob/master/lib/rdoc/generator/template/rails/_head.rhtml#L6

**Comment by DiegoOrejuela** [comment]
@p8 but this break turbolinks, no?

**Comment by DiegoOrejuela** [comment]
okey, I already checked  change the rel_prefix and works except what solves #135 . Everything as expected. However, perhaps a setting can be added to determine whether the user wants to use the rel_prefix or not, taking into account its pros and cons. @p8 what do you think?

**Comment by p8** [comment]
@DiegoOrejuela  Sounds good!

**Comment by DiegoOrejuela** [comment]
@p8 is it open to PR?

**Comment by p8** [comment]
@DiegoOrejuela  Sure!
Maybe an ENV variable like:
https://github.com/zzak/sdoc/blob/master/lib/rdoc/generator/template/rails/index.rhtml#L14

**Comment by DiegoOrejuela** [comment]
@p8 Well, I have some bad news. Actually in local it does not work. It worked for me because I had not noticed that when I open the index from Rubymine what it does is serve it in a kind of server, but when going directly to the file in my file system it fails. So I decided to create a simple rake server to serve it, following the example of the config.ru in this gem. With this, then I don't really see the 'rel_prefix' thing working. Thank you anyway.

**Comment by p8** [comment]
@DiegoOrejuela Thanks for having a look. 👍  I'll try to have a stab at it as well..

**Comment by p8** [comment]
The latest release uses relative paths making it work locally as well.
Locally the sidebar doesn't work but this should be fixed in: https://github.com/zzak/sdoc/pull/182
