### ISSUE TITLE
Improve Lighthouse Score

### ISSUE THREAD

**Issue by MikeRogers0** [zzak/sdoc#151]
![image](https://user-images.githubusercontent.com/325384/109213803-f7c49a00-77a8-11eb-9248-66dd2580be7e.png)
![image](https://user-images.githubusercontent.com/325384/109213839-feeba800-77a8-11eb-9a5a-46e7c843fa7e.png)

I'd love to do some work on improve the current [lighthouse scores](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fapi.rubyonrails.org%2F), mainly around accessibility & performance :)

What is your preferred way for me to chip away at these? I'm thinking I try to create PRs when I can, focusing on the quick wins first then moving onto the harder stuff as I get more confident in the codebase.

**Comment by p8** [comment]
@MikeRogers0 Sounds great! Smaller PR's  are easier to review/merge.

**Comment by MikeRogers0** [comment]
I'm super excited for https://github.com/zzak/sdoc/pull/154 - I reckon that'll improve the scores massively :D

The next thing I'm going to attempt do is try to compile some of the CSS/JS into single files. I might try to setup a fun netlify preview system as part of that if you'd like? :)

**Comment by MikeRogers0** [comment]
![image](https://user-images.githubusercontent.com/325384/114550773-7d69af80-9c5a-11eb-9b07-c83a07356893.png)


Scores have massively improved when I test this against our Netlify preview app. Nice work everyone :)

**Comment by p8** [comment]
Maybe we should also add caching to the assets and lazily build the panel tree (only create dom elements when clicking).
https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fedgeapi.rubyonrails.org%2F

**Comment by p8** [comment]
Ah, you already created an issue :)
https://github.com/rails/rails-docs-server/issues/25

**Comment by MikeRogers0** [comment]
> Maybe we should also add caching to the assets

I did make a PR also ( https://github.com/rails/rails-docs-server/pull/24 ), but it didn't get much traction :/ Plus their setup appears to be a single server based in the USA (Over a CDN, which I think would be much more effective).
Any ideas of how to help the Rails team with their setup @p8 ?

> lazily build the panel tree (only create dom elements when clicking).

This would be really cool!
