### ISSUE TITLE
Add Netlify preview for Pull Requests

### ISSUE THREAD

**Issue by MikeRogers0** [zzak/sdoc#162]
I added a Netlify preview to a few of my PRs ( e.g. https://github.com/zzak/sdoc/pull/161 ), which I think adds a lot of value to help a change be reviewed.

Is there any interest in setting up something on this repo? I'd happily help out, but want to make sure it's wanted :)

**Comment by SleeplessByte** [comment]
If you add this, I will commit 1hr / week reviewing whatever you want reviewed, in order to get the docs to be more accessible. Pulling, building, testing is a bit time consuming!

**Comment by MikeRogers0** [comment]
I'm also happy to commit 1hr / week to this project :)

**Comment by MikeRogers0** [comment]
![image](https://user-images.githubusercontent.com/325384/114550328-f7e5ff80-9c59-11eb-8638-011950a673b9.png)

https://github.com/zzak/sdoc/pull/161 - This is in & looking really good! Thank you @zzak :D
