### ISSUE TITLE
Add some meta tags for SEO

### ISSUE THREAD

**Issue by okuramasafumi** [zzak/sdoc#190]
[META SEO inspector](https://chrome.google.com/webstore/detail/meta-seo-inspector/ibkclpciafdglkjkcibmohobjkcfkaef) points out some problems such as there's no "description" meta tag.
It's easy to fix and good for SEO, so if we agree how to implement it, I'd like to send a patch.

**Comment by p8** [comment]
Hi @okuramasafumi
We do have it on the class pages:
https://github.com/zzak/sdoc/blob/d4f8476ca881b400e7d72fe734a768cc73e63cf9/lib/rdoc/generator/template/rails/class.rhtml#L13

**Comment by okuramasafumi** [comment]
Sorry I missed that, thanks!
What about missing canonical URL?

**Comment by p8** [comment]
That would be really nice. ❤️ 
See also this issue https://github.com/rails/rails/issues/45880

**Comment by zzak** [comment]
I've created rails/rails#47328 to set the canonical url as an environment variable for us. :pray: Open to suggestions or other ideas!
