### ISSUE TITLE
stuck on Generating SDoc

### ISSUE THREAD

**Issue by elfassy** [zzak/sdoc#82]
On version 0.4.0+ i get stuck on

```
Generating SDoc format into .../doc...
```

With version 0.3 it all works fine.

**Comment by zzak** [comment]
What project were you trying to generate documentation for?

Generation can take a while, depending on the project and your environment.. but it certainly should finish (eventually)

**Comment by robin850** [comment]
We can certainly give this a close ; feel free to comment and we can reopen if this problem still exists with modern (S|R)Doc. Thanks for reporting anyway !
