### ISSUE TITLE
Don't work well with inline private

### ISSUE THREAD

**Issue by Paxa** [zzak/sdoc#85]
```ruby
class Example
   def public_method1; end

  private def private_method; end

  def other_public_method; end
end
```

sdoc see other_public_method as private method

**Comment by zzak** [comment]
This is the way RDoc treats the private keyword, and unrelated to SDoc.. but we should be able to fix it

**Comment by zzak** [comment]
Closing this since it's already been reported upstream in rdoc/rdoc#354 and rdoc/rdoc#355

Thank you!
