### ISSUE TITLE
ActionController::ActionController::ActionController :D

### ISSUE THREAD

**Issue by chancancode** [zzak/sdoc#88]
Today we discovered that on the [Rails documentation site](http://api.rubyonrails.org) we have an entry for [`ActionController::ActionController::ActionController`](http://api.rubyonrails.org/classes/ActionController/ActionController/ActionController.html). From [here](http://api.rubyonrails.org/classes/ActionController/ActionController.html), I suspect that the problem might be caused by lines like [these](https://github.com/rails/rails/blob/861b70e92f4a1fc0e465ffcf2ee62680519c8f6f/actionpack/lib/action_controller/metal/live.rb#L303), but I am not 100% sure.

**Comment by chancancode** [comment]
cc @fxn @zzak

**Comment by zzak** [comment]
Would help if we could reproduce it without sdoc

**Comment by fxn** [comment]
@zzak could it be possible to patch RDoc locally to print a trace when the constant path is built? The first couple would be enough.

**Comment by zzak** [comment]
I need to determine if this is a bug in sdoc or rdoc

**Comment by aycabta** [comment]
I identified the problem and reproduce it by the code below:

```ruby
module A
  class A::B
  end
end
```

When you save it as `a.rb` and run `rdoc a.rb`, the `doc/A/A/A.html` is generated for `A::A::A`. It's bug of RDoc. Please wait, I'll fix it.

**Comment by aycabta** [comment]
This fixes by https://github.com/ruby/rdoc/pull/523.

**Comment by robin850** [comment]
Thank you very much @aycabta !
