### ISSUE TITLE
undefined local variable or method `rel_prefix' for #<RDoc::Generator::SDoc:0x007f73ee909ae8>

### ISSUE THREAD

**Issue by manuelmeurer** [zzak/sdoc#92]
I updated RubyDocs.org to use sdoc master and I have been seeing `undefined local variable or method rel_prefix for #<RDoc::Generator::SDoc:0x007f73ee909ae8>` errors since then.
Backtrace:
```
"/var/www/rubydocs/vendor/bundle/ruby/2.2.0/bundler/gems/sdoc-e5b47faa3e75/lib/rdoc/generator/template/sdoc/file.rhtml" line 8 in block in generate_file_files
"/home/chief/.rbenv/versions/2.2.2/lib/ruby/2.2.0/erb.rb" line 863 in eval
"/home/chief/.rbenv/versions/2.2.2/lib/ruby/2.2.0/erb.rb" line 863 in result
"/var/www/rubydocs/vendor/bundle/ruby/2.2.0/bundler/gems/sdoc-e5b47faa3e75/lib/sdoc/templatable.rb" line 13 in eval_template
"/var/www/rubydocs/vendor/bundle/ruby/2.2.0/bundler/gems/sdoc-e5b47faa3e75/lib/sdoc/templatable.rb" line 35 in render_template
"/var/www/rubydocs/vendor/bundle/ruby/2.2.0/bundler/gems/sdoc-e5b47faa3e75/lib/sdoc/generator.rb" line 324 in block in generate_file_files
"/var/www/rubydocs/vendor/bundle/ruby/2.2.0/bundler/gems/sdoc-e5b47faa3e75/lib/sdoc/generator.rb" line 319 in each
"/var/www/rubydocs/vendor/bundle/ruby/2.2.0/bundler/gems/sdoc-e5b47faa3e75/lib/sdoc/generator.rb" line 319 in generate_file_files
"/var/www/rubydocs/vendor/bundle/ruby/2.2.0/bundler/gems/sdoc-e5b47faa3e75/lib/sdoc/generator.rb" line 175 in generate
```

I'm guessing it has something to do with [this commit](https://github.com/zzak/sdoc/commit/d19ec3452172ceb5335981b79f4cdbba41be3a79) but I can't immediately see what the problem is since you basically just added back the `rel_prefix` assignments. Maybe because `attr_reader :rel_prefix` was added? What was the purpose of that?

**Comment by zzak** [comment]
Ahh, I thought I fixed this but not sure if I pushed the commit yet.

**Comment by zzak** [comment]
@manuelmeurer Let me know if this fixes it for you!

**Comment by manuelmeurer** [comment]
Ok, I'll try it, cheers!

**Comment by manuelmeurer** [comment]
Seems like that did the trick, thanks! Do you plan to release a new version soon?

**Comment by zzak** [comment]
@manuelmeurer Yes! I'm going to do a bugfix release of rdoc first though.
