### ISSUE TITLE
Ruby 2.4.0-preview2 needs json 2.0.2

### ISSUE THREAD

**Issue by jasnow** [zzak/sdoc#97]
Ruby 2.4.0-preview2 needs json 2.0.2: 
Can you please loosen up the dependency in sdoc.gemspec?
Thanks.

**Comment by jasnow** [comment]
@zzak - Would an example repo help to demo this?

**Comment by yahonda** [comment]
I think #96 addresses this behavior. I also wanted it gets fixed to run ActiveRecord master branch using ruby 2.4.0.preview2.

**Comment by zzak** [comment]
Should be fixed in 1.0.0.beta1

**Comment by jasnow** [comment]
Agreed it is fixed.
