### ISSUE TITLE
Ruby 2.4 compatibility

### ISSUE THREAD

**Issue by tom-lord** [zzak/sdoc#99]
In case anyone else encounters this issue too...

Version `0.4.2` of this gem relies on `json ~> 1.7`, which resolves to `v1.8.3` - as defined in [this line](https://github.com/zzak/sdoc/blob/6aeb1ef3827afecc9ae35c24845dd9fa37420388/sdoc.gemspec#L25).

However, the `json v1.8.3` gem is [not compatible](https://github.com/flori/json/issues/303) with ruby 2.4.

This issue was resolved in this gem [here](https://github.com/zzak/sdoc/commit/c28efc8d4ebe0a50ed1072f3e4041657b149b634#diff-2be1af0ba66e7660b4bd6eaeb8cf8c4d), by changing the gem's dependencies.

However, since `v1.0.0` of this gem has not yet been released, in order to use this gem within a ruby 2.4 project you must currently place something like this in your `Gemfile`:

```
group :doc do
  gem 'sdoc', '1.0.0.rc1', require: false
end
```

**Comment by zzak** [comment]
Thank you @tom-lord! I will make a final release :soon:!!

**Comment by stoivo** [comment]
How soon?

**Comment by tom-lord** [comment]
This is less of an issue now since [`json v1.8.5`](https://rubygems.org/gems/json/versions/1.8.5) was released (after I raised this issue), which adds support for ruby `2.4`.

In the [issue linked above](https://github.com/flori/json/issues/303), the gem maintainers originally stated that compatibility for ruby `2.4` would not be added for `json 1.8.x`, then later changed their minds.

**Comment by tom-lord** [comment]
...So I'll close this issue now, but it would still be good to see a [`v1.0.0` release!](https://rubygems.org/gems/sdoc/versions/1.0.0.rc2)
